### ISSUE TITLE
Re-design Compose interface and provide ability to edit posts

### ISSUE THREAD

**Issue by legendword** [legendword/blog#27]
- [x] Backend code for post edits
- [ ] Backend code testing/debugging
- [x] Redesign Compose page
- [ ] Add post editing feature

**Comment by Lisherex** [comment]
- [ ] Draft feature

**Comment by legendword** [comment]
On second thought, providing the ability to edit blog posts is troublesome as it defies data consistency. We want the contents of blogs to be constant so others can access the exact same information with the permalinks. More workarounds on editing blog content can be discussed in the future.

The draft feature is, however, still on the development schedule.
